server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**.xml